import { Component } from '@angular/core';

@Component({
  selector: 'app-Account',
  templateUrl: './Account.component.html',
  styleUrls: ['./Account.component.css'],
})
export class AccountComponent {
  displayedColumns: string[] = [
    'rank',
    'name',
    'points',
    'gp',
    'win',
    'lose',
    'draw',
    'winPercentage',
    'actions',
  ];
  players = [
    {
      rank: 1,
      name: 'Player1',
      points: 12,
      gp: 4,
      win: 4,
      lose: 0,
      draw: 0,
      winPercentage: '100%',
    },
    {
      rank: 2,
      name: 'Player2',
      points: 10,
      gp: 4,
      win: 3,
      lose: 1,
      draw: 0,
      winPercentage: '75%',
    },
    {
      rank: 3,
      name: 'Player3',
      points: 5,
      gp: 3,
      win: 1,
      lose: 2,
      draw: 0,
      winPercentage: '33.3%',
    },
    {
      rank: 4,
      name: 'Player5',
      points: 3,
      gp: 3,
      win: 0,
      lose: 3,
      draw: 0,
      winPercentage: '0%',
    },
    {
      rank: 5,
      name: 'Player7',
      points: 3,
      gp: 1,
      win: 1,
      lose: 0,
      draw: 0,
      winPercentage: '100%',
    },
    {
      rank: 6,
      name: 'Player8',
      points: 3,
      gp: 1,
      win: 1,
      lose: 0,
      draw: 0,
      winPercentage: '100%',
    },
    {
      rank: 7,
      name: 'Player4',
      points: 2,
      gp: 2,
      win: 0,
      lose: 2,
      draw: 0,
      winPercentage: '0%',
    },
    {
      rank: 8,
      name: 'Player6',
      points: 2,
      gp: 2,
      win: 0,
      lose: 2,
      draw: 0,
      winPercentage: '0%',
    },
  ];
}
